### ISSUE TITLE
Decouple authentication implementation

### ISSUE THREAD

**Issue by joaoeduardo** [lavender/framework#1]
The authentication implementation is amazing. Is possible to decouple it, to use in another projects?

**Comment by ryaan-anthony** [comment]
so, the authentication package is a custom blend of [multiauth](https://github.com/ollieread/multiauth) and [confide](https://github.com/Zizaco/confide/) but cleaned up and optimized for Lavender. It shares Lavender's Entity model to provide Account and Reminder objects, which could be refactored out with some minor head-scratching. 

but to directly answer your question, yes definitely, i'll spend some time looking into this. i think there is plenty of merit in decoupling the components, especially Auth and Entity.
